### ISSUE TITLE
The MT() macro does not respect shift

### ISSUE THREAD

**Issue by kuporific** [jackhumbert/qmk_firmware#103]
Suppose a key assigned to one of

    MT(MOD_LCTL, KC_EXLM)
    CTL_T(S(KC_1))
    etc...

When that key is pressed, it produces a `1` rather than the expected `!`. (When holding a Shift key, however, it does produce a `!`.) This behavior happens for all `MT` modifiers and all key definitions that have shift pre-applied (e.g. `KC_TILD`, `KC_AT`, `KC_HASH`, etc.)

**Comment by jackhumbert** [comment]
Check out #50!
