### ISSUE TITLE
No media keys on ErgoDox?

### ISSUE THREAD

**Issue by Flink** [jackhumbert/qmk_firmware#111]
Hi!

I’m using an ErgoDox (not an EZ one) with this firmware and I found that media keys are not working. They just send nothing.
I’m just using this firmware since yesterday (just received my ErgoDox) so maybe there’s something I missed?

**Comment by Eric-L-T** [comment]
What is your operating system? Have you seen [this](https://github.com/tmk/tmk_keyboard/wiki/FAQ-Keymap#media-control-keys-in-mac-osx)?

**Comment by Flink** [comment]
I’m using linux. Thank you for the link but the chibios does not apply on an ergodox, does it? And if it is the case how to use it please? (Also it seems weird that the firmware used by the ErgoDox EZ doesn’t send multimedia keys)

**Comment by Flink** [comment]
So I read the FAQ and I didn’t see anything about my problem. I may have missed something though.

**Comment by ezuk** [comment]
Hey @Flink - so the short answer is I don't know. :) The media keys on the EZ work fine on a PC, and the Mac layout lets people use them on a Mac. I've yet to receive any questions for the EZ re media keys for Linux. 

I'm sorry I'm not able to support just ErgoDox DIY users -- I really wish I could, but if you try running a product like this you'll realize just how much work it is... I'm afraid right now I can only offer personal one-on-one support to ErgoDox EZ customers. It's not because I'm evil, just because of a simple time constraint. I'm sorry and I hope you can understand!

**Comment by DidierLoiseau** [comment]
@ezuk I confirm the media keys work fine on Ubuntu with the ErgoDox EZ.

@Flink have you checked the output of `xev` when you press the media keys? Also, you might want to compile and run your keyboard in debug mode with `hid_listen`, it's not very hard to configure.

**Comment by Flink** [comment]
@ezuk No problem, I understand perfectly. But this firmware should work without any problem on an ErgoDox DIY no?

@DidierLoiseau Yes I checked and there is no output at all :/ Could you point me towards resources to enable and use this `hid_listen` debug mode please?

**Comment by jackhumbert** [comment]
It should - do you have your code forked that we could look at? Have you tried any other OSes?

**Comment by Flink** [comment]
@jackhumbert my keymap is here: https://github.com/Flink/qmk_firmware/blob/bepo-flink/keyboard/ergodox_ez/keymaps/bepo_flink/keymap.c
And no I didn’t try with another OS, I’ll try on windows and report back.

**Comment by jackhumbert** [comment]
Quick sanity check - your keyswitches work when you're using a different keycode, right? Just wanna make sure it's not a hardware thing.

What linux flavour/environment are you running?

**Comment by Flink** [comment]
Yeah keys on the main layer are working as expected and I swapped some keys previously that were also working fine.

I’m running an Archlinux.

**Comment by Flink** [comment]
@jackhumbert I just did the test on Windows and the media keys are working as expected. So it seems it’s not working on my arch. That’s strange, could it be a permission problem related to udev or something like that? (my previous keyboard, a typematrix 2030, was sending media keys correctly, I don’t know if it can help)

**Comment by krasnovu** [comment]
I have planck keyboard and keycodes like KC_MPLY, KC_MNXT, KC_VOLU... not works in win 7, but works on ubuntu 14.04

**Comment by Flink** [comment]
@krasnovu forgot to precise, I tested with Windows 10 and KC_CALC, KC_VOLU, KC_VOLD and KC_MUTE are all working.

**Comment by Flink** [comment]
Ok, found the issue, it’s the same as described here: https://bbs.archlinux.org/viewtopic.php?id=178838
Since I don’t use any joystick under linux, I just removed the `xf86-input-joystick` package and now I have working media keys :grin:
