### ISSUE TITLE
Registering key tap on press

### ISSUE THREAD

**Issue by uzytkownik** [jackhumbert/qmk_firmware#114]
I haven't found a way to do it so I'm posting it as a bug (in worst case it's a bug of documentation). I'm trying to write custom key bindings to ErgoDox and I'd like one key to send tap of RCtrl and then press down of LGui on press down and press up of LGui on press up. Is that possible?

**Comment by uzytkownik** [comment]
Ok. I misunderstood the documentation

**Comment by ezuk** [comment]
@uzytkownik - what could have been clearer? Happy to tweak the docs.
