### ISSUE TITLE
Undocumented coder toggle behaviour in Ergodox-EZ.

### ISSUE THREAD

**Issue by fuzzbomb** [jackhumbert/qmk_firmware#132]
The default Ergodox-EZ layout diagram says the RH bottom-right key is "Tmp Coder Layer".

In fact it does more than that, due to the custom behaviour of `KC_FN1` defined in the default Ergodox-EZ `keymap.c` file:

- Tapping the key momentarily, it behaves as a permanent toggle for the coder layer. 
- Tap-and-hold, it temporarily activates the coder layer.

Can we get the keyboard layout images updated? I don't know what your workflow is for updating them (they're just PNGs; maybe you have a Photoshop file or something).

**Comment by ezuk** [comment]
Done! :) Also added a dual-function quote/Cmd key for the default layout. Thanks!
