### ISSUE TITLE
ergodox_ez default keymap: hex not applying cmd when apostrophe is held

### ISSUE THREAD

**Issue by dudymas** [jackhumbert/qmk_firmware#143]
So I went ahead and nabbed the latest hex file from [keyboard/ergodox_ez/keymaps/default](keyboard/ergodox_ez/keymaps/default) since I saw the recent update to it.

From what I can tell, the hex flashes successfully, and teensy reboots just fine, but holding down apostrophe ( `'` ) yields no change. I just see apostrophe in my keymap.

I tried unplugging the ergodox to make sure, but indeed... I think the hexfile is bad. Can someone else confirm?

Here's the md5 for the hex file I got when I cloned this repo to my disk: `29fbf9fe505b911892007dd07bf01933`
If you do get the CMD to work, please make sure the MD5 matches that... or maybe someone didn't push the hex file? I'm rather new to teensy and don't have the setup yet to compile and confirm this myself.

**Comment by ezuk** [comment]
That's pretty weird -- this is the exact checksum I'm showing, and i just flashed this file and holding down ' (the right-hand pinky key in the third row) pops open the Start menu on Windows and sends Cmd on Mac. Would you mind sharing a pic or something showing exactly what key you're hitting?

**Comment by dudymas** [comment]
Aha, okay, figured it out. I simply didn't understand the teensy programmer.
I was clicking the reboot button and not the reprogram button. :-/ I always assume if the arrow looks like a cycle, that's reboot, and if the arrow looks like it's pushing, then it's sending data. Durp.

Sorry about the confusion. And indeed, the apostrophe DOES map to the meta key now.
Closing.

**Comment by ezuk** [comment]
Oh, nice! Thank you @dudymas!
