### ISSUE TITLE
KC_NUHS same as KC_BSLS

### ISSUE THREAD

**Issue by HugoNikanor** [jackhumbert/qmk_firmware#167]
KC_NUHS  (and its long form: KC_NONUS_HASH) gives the characters of KC_BSLS ('\' & '|') instead of a tilde or a "non us hash" as the guide suggests https://github.com/jackhumbert/qmk_firmware/blob/master/tmk_core/doc/keycode.txt

**Comment by jackhumbert** [comment]
I believe this depends on the OS's layout - some languages use it as a hash, others don't!
