### ISSUE TITLE
1-setup-path-win.bat can corrupt your Windows system

### ISSUE THREAD

**Issue by IBNobody** [jackhumbert/qmk_firmware#198]
Just a heads-up, Jack. On Windows systems with existing and lengthy PATH environmental variables, SETX will corrupt your system.

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>setx /M path "%PATH%;C:\MinGW\bin;C:\MinGW\msys\1.0\bin"

**WARNING: The data being saved is truncated to 1024 characters.**

SUCCESS: Specified value was saved.

C:\Windows\system32>
```

Since you mask the output to null, the user only sees "Success!", not the "oh by the way, your PATH statement is now corrupted" warning hint.

**Comment by NoahAndrews** [comment]
Oh. Sorry for that. :anguished: Thanks for spotting this. (I was the one who wrote the offending script.) WHY doesn't Microsoft document this properly? I found an alternate solution and will submit a pull request.

**Comment by IBNobody** [comment]
::Raises fist to the sky:: MICROSOFT!!!!

Seriously, though... Which fix are you going to use? SETX was nice because it sent out the notification that the env vars were changing. That is needed to tell Windows that you've updated the path.

**Comment by NoahAndrews** [comment]
I think I'll modify the registry directly, and then use SETX to rewrite NUMBER_OF_PROCESSORS or something with itself. That way Windows will know that something changed.

**Comment by IBNobody** [comment]
Maybe write to a scratch envvar, like SETX FOO=BAR, then delete it with SETX FOO=?

**Comment by NoahAndrews** [comment]
only SET FOO= works, not SETX FOO=.

**Comment by NoahAndrews** [comment]
https://github.com/jackhumbert/qmk_firmware/pull/223

**Comment by IBNobody** [comment]
I rewrote the fix after testing it extensively. The problem is that Explorer.exe holds onto the old values no matter what. My new code restarts Explorer. (Take that, Windows!)

Hats off to @NoahAndrews for the initial idea.

**Comment by NoahAndrews** [comment]
Why does it matter if explorer.exe holds onto the values?

**Comment by IBNobody** [comment]
If you execute the batch file by double-clicking or if you execute it by opening a shift-right-click command prompt, Explorer retains the value of the environment variables. Even setx will not budge it. (Or at least setx setting a different key won't budge it.)

Thus, you can run into problems when you try to run your second batch file. The second batch file will fail on the first mingw-get call for systems that did not have the env vars set prior to the first batch file being run.

**Comment by NoahAndrews** [comment]
Ah. :/
