### ISSUE TITLE
teensy_loader_cli does not exist  (tmk_core/rules.mk)

### ISSUE THREAD

**Issue by jsprada** [jackhumbert/qmk_firmware#225]
On my system, I have teensy-loader-cli installed (dashes, rather than underscores), which causes an error in rules.mk (tmk_core) when running `# make teensy`

    415: teensy_loader_cli -mmcu=$(MCU) -w -v $(TARGET).hex

I manually edited my local copy (replaced the underscores with dashes) which seemed to work just fine for me.  I'm not sure if the program is installed under a different name for other systems.  I installed teensy-loader-cli from the AUR.

Thank you,
Johnny

**Comment by jackhumbert** [comment]
Ah, #231 makes sense now. I'm unsure what should be done here, but I think I'd like to leave it as the default (underscores).
