### ISSUE TITLE
Waking up Mac from sleep

### ISSUE THREAD

**Issue by janv** [jackhumbert/qmk_firmware#237]
I'm using an Ergodox EZ with the QMK firmware.
The keyboard does not seem to be able to wake my Mac from sleep.
Is there a way to make that work?

**Comment by ezuk** [comment]
Sure! See: https://github.com/tmk/tmk_keyboard/wiki/FAQ

Specifically:

Wakeup from sleep doesn't work

In Windows check Allow this device to wake the computer setting in Power Management property tab of Device Manager. Also check BIOS setting.

Pressing any key during sleep should wake host.

**Comment by ezuk** [comment]
Did you try `KC_WAKE` and `KC_PWR`?

**Comment by jackhumbert** [comment]
You might need to hold down the key as well - it doesn't help that OSX's sleep sucks :/

**Comment by janv** [comment]
Hm, could't get it to work.
But it's not that big a deal I guess, I can use my mouse to wake up the computer

**Comment by jtbandes** [comment]
I'm experiencing this as well. I'll try KC_WAKE/PWR soon.

But why is this necessary? Other keyboards/mice I've used (usually Apple ones) always seem to wake the machine when something is pressed, not just the power key.

**Comment by cleung2010** [comment]
I am experiencing the opposite issue on the Planck, where the keyboard stops working after a wakeup. The backlights are still on, so I know that it's not a power issue. 

This started occurring after I updated the firmware to the commit `2cf26915e3ed737ae83cf7b54f7e84fc2f0d3b40` (Jun. 16). Before that, I was running on the build from `3c683aa9f23288ddada760fb49abcc5fa7324f5e` (Feb. 7) with no problems.

The custom keymap that I flashed is based off `default` with some keys swapped, but no major changes.

**Comment by jackhumbert** [comment]
@cleung2010 what OS are you on? I've had something similar recently, where the matrix seems to be acting up. I'm wondering if it's related to #444.

**Comment by cleung2010** [comment]
This is on OSX El Capitan.

**Comment by janv** [comment]
I updated my firmware last week and at least pressing `SPACE` now seems to wake up my mac

**Comment by bennypowers** [comment]
I have this same issue. Shouldn't have to issue a special `WAKE` command - any keypress should wake from sleep.
