### ISSUE TITLE
KC_AT with right shift

### ISSUE THREAD

**Issue by moonrumble** [jackhumbert/qmk_firmware#240]
Instead of numbers, I have used their shift counterpart. 

While I am still getting used to my layout. I often press right shift key and press KC_AT key. 

If I press LSHIT and KC_AT, it prints KC_AT but if I press RSHIFT and KC_AT it changes the layer to next layer.

**Comment by moonrumble** [comment]
https://github.com/moonrumble/qmk_layout/blob/master/keymap.c

**Comment by ezuk** [comment]
Is there a particular reason why you're even using RSHIFT? What happens if you define both Shift keys on your keyboard as LSHIFT? Do you get any ill effects?

**Comment by jackhumbert** [comment]
There's some fancy stuff with KC_AT going on behind the scenes - my guess is that right shift gets combined with KC_AT (which is really LSFT and KC_2) to switch to layer 2. I think that's a magic key combo to switch to layer *x*, but I could be mistaken, and it could have to do with the bits passed around by both shifts.

**Comment by ezuk** [comment]
Ah right - so RSHFT + KC_AT really means RSHFT + LSHFT + 2. So having both shift keys as LSHFT should resolve.

**Comment by jackhumbert** [comment]
You can also change the command combo [here](https://github.com/jackhumbert/qmk_firmware/blob/master/keyboard/ergodox_ez/config.h#L66) - let us know if it works!
