### ISSUE TITLE
Default Preonic README.md is the same as the Planck and is incorrect.

### ISSUE THREAD

**Issue by tballas** [jackhumbert/qmk_firmware#251]
Default Preonic README.md is the same as the Planck and is incorrect.

This:
https://github.com/jackhumbert/qmk_firmware/blob/master/keyboard/preonic/keymaps/default/README.md

Doesn't match:
https://github.com/jackhumbert/qmk_firmware/blob/master/keyboard/preonic/keymaps/default/keymap.c

**Comment by jackhumbert** [comment]
Yeap! The layout is still being finalised :)
