### ISSUE TITLE
RGUI and RALT seem to be mixed up

### ISSUE THREAD

**Issue by sboesebeck** [jackhumbert/qmk_firmware#259]
I recently re-compiled the firmware and RGUI and RALT seem to be mixed up. If you assign RGUI to a key, it's actually RALT and vice versa

**Comment by jackhumbert** [comment]
Can you try unplugging the board, holding RALT & space and plugging it in?

Sound like bootmagic :)

**Comment by sboesebeck** [comment]
tried that just now - problem solved! thanks

**Comment by jackhumbert** [comment]
Perfect!

**Comment by KaarelP2rtel** [comment]
OOC what bootmagic are we talking about and how could his be avoided?
