### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by trungphamasnet** [jackhumbert/qmk_firmware#263]
![image](https://cloud.githubusercontent.com/assets/696416/14627369/e91e5efc-061d-11e6-95be-260ae632bef0.png)
build on windows 10
please help me

**Comment by NoahAndrews** [comment]
Are you using WinAVR? That's a known problem with WinAVR on modern versions of Windows. Uninstall WinAVR and install the MHV AVR Tools instead. https://infernoembedded.com/products/avr-tools

**Comment by trungphamasnet** [comment]
done
thank you @NoahAndrews
