### ISSUE TITLE
quantum code not included in phantom make files

### ISSUE THREAD

**Issue by jarions** [jackhumbert/qmk_firmware#266]
The quantum additions such as M(), F() do not compile for the phantom keyboard (Makefile.prjc).  I have attempted to use the new project script to create a new phantom keyboard layout.  it compiles with the M() and F() aliases but locks up the teensy upon loading.

Do you have any tips on what I should do to get this working?  I am a programmer but I'm not very familiar with C++ and make.

Thanks,
js

**Comment by jackhumbert** [comment]
Sorry about that! Not all of the projects have been updated to what quantum requires - if you'd like to update it, check out the /keyboard/planck, /keyboard/atomic, or /keyboard/preonic folders for how things should be structured.

There's an update going on right on, so I'm not entirely sure the new project script is up-to-date. If you can fork the code and upload your changes, we might be able to take a look at things closer.
