### ISSUE TITLE
README: More Technical: doesn't say where keymaps/ is

### ISSUE THREAD

**Issue by adiabatic** [jackhumbert/qmk_firmware#290]
I got a little lost on step 4: it says to copy `keymaps/default/keymap.c` elsewhere, but it doesn't mention that `keymaps/` is in `…/qmk_firmware/keyboard/ergodox_ez`. Could the instructions be updated to nudge the user in the right direction of the proper subirectory?

**Comment by ezuk** [comment]
Thanks for the feedback! Done.
