### ISSUE TITLE
register_code() not working properly.

### ISSUE THREAD

**Issue by nemoNoboru** [jackhumbert/qmk_firmware#316]
calling 
register_code(KC_AT);
unregister_code(KC_AT);
writes "2" not an "@" as intended.

**Comment by eltang** [comment]
`KC_AT` is a special alias. When you feed it to `register_code` it will truncate the part that contains the Shift. You must write code like this.

```c
register_mods(MOD_BIT(KC_LSFT));
register_code(KC_2);
unregister_code(KC_2);
unregister_mods(MOD_BIT(KC_LSFT));
```

**Comment by nemoNoboru** [comment]
thanks eltang!
