### ISSUE TITLE
Enable/Disable Plover when toggling the Plover Layer

### ISSUE THREAD

**Issue by cwhits** [jackhumbert/qmk_firmware#322]
There's a keyboard shortcut in plover for toggling whether output is enabled or disabled. Would it make sense to add this? Is it universal between Mac/Windows/Linux?

**Comment by jackhumbert** [comment]
Sure! There's a couple of free spaces on the Planck Plover layer - do you know what it is in the default Plover setup?

**Comment by cwhits** [comment]
So, the only issue with that pull request is you'll see `erfvol` if plover isn't open. It's convenient if it _is_ open that you don't have to do any extra keystrokes and makes it function the same as changing any other layer. I could see the benefit of having the toggle be a completely separate key though.

Let me know your thoughts.

**Comment by jackhumbert** [comment]
Ah, I thought it might have been tied to an actual key on the keyboard. Let's hold off on that, then - I'd like for people to be able to switch to the Plover layer without a bunch of things printing out.

**Comment by eltang** [comment]
@jackhumbert Have the default keymaps been finalized yet?
