### ISSUE TITLE
ErgoDox Ez VS Original?

### ISSUE THREAD

**Issue by braidn** [jackhumbert/qmk_firmware#37]
Hey all, 

I currently have an original Ergodox and was wondering if uploading the .hex generated from the Ergodox ez dir will work for my board? I am assuming it will but thought I would ask. Thanks and love what you are doing with things.

**Comment by jackhumbert** [comment]
Erez can correct me if I'm mistaken, but I believe it uses the same IO expander/chipset/matrix wiring, so it should! We pulled out support for the left-side LEDs, but they're pretty easy to add back in!

**Comment by RageZBla** [comment]
I personally tested it yesterday and yes it works. :+1:

**Comment by ezuk** [comment]
Oh, totally! This should work for the original ErgoDox -- glad to see that it does :)
