### ISSUE TITLE
How to get to /keyboard in VM now that Vagrantfile has been relocated to /util?

### ISSUE THREAD

**Issue by stanleylai** [jackhumbert/qmk_firmware#379]
Going into /vagrant in the VM only shows files that are in /util. Can't figure out a way to navigate to /keyboard to compile hex files?

**Comment by jackhumbert** [comment]
Ah, sorry about that - that may need to be relocated to the root folder!

**Comment by stanleylai** [comment]
Haha awesome. Thanks for the quick reply Jack! Thought I must have missed something :)

**Comment by jackhumbert** [comment]
You might need to modify the `avr_setup.sh` (line 71) in the Vagrantfile as well - can you let me know if that's needed?

**Comment by stanleylai** [comment]
Yep, it needs a ./util/avr_setup.sh

**Comment by jackhumbert** [comment]
Great - thanks!

**Comment by stanleylai** [comment]
Issue resolved. Closing.
