### ISSUE TITLE
Color output during make

### ISSUE THREAD

**Issue by jackhumbert** [jackhumbert/qmk_firmware#383]
Are there any good reasons for not doing this? It could make things a bit more informative.

**Comment by skullydazed** [comment]
As long as there's both a way to turn it off and it's smart enough to only colorize output when stdout is a tty, I don't see any reasons for not doing it.

(I don't think it helps much, personally, but lots of people seem to benefit from color.)

**Comment by jackhumbert** [comment]
Added this at a785b00 for messing around with - really only does the warnings/errors, but is useful to see what's wrong. Haven't added the conditional to it yet.

**Comment by ezuk** [comment]
Oooh, colors! 🌈

**Comment by jackhumbert** [comment]
Here's a preview of the make reformatting:
![screen shot 2016-06-06 at 11 49 08 pm](https://cloud.githubusercontent.com/assets/141431/15845465/5e8aaf80-2c41-11e6-826e-813ad610cd31.png)

**Comment by ezuk** [comment]
Super nice. Very clear. Makes me want to fix all the warnings :)

**Comment by jackhumbert** [comment]
Merged in from #395!
