### ISSUE TITLE
Explaining more in details what do KC_TRNS

### ISSUE THREAD

**Issue by mystcreater** [jackhumbert/qmk_firmware#390]
Hi,

I've completed my new layout a couple of days ago and it works fine. I used the default keymap and a change a couple of things. Today, I was surprise to understand that KC_TRNS is not a code for set to empty a key (KC_NO) but to inherit from the code of the previous layer. I figure that when typing a key which I was thinking will do nothing but the result was the letter of the previous layer. 

After thinking more about that, I note this is totally obvious considering the place in the documentation indicating that you must set this code to the x + 1 layer associated with a key that change layer if you not want to but stuck at this layer. However, I don't found any documentation at (https://github.com/jackhumbert/qmk_firmware/blob/master/doc/keycode.txt) about the behavior of this code. 

Thanks.

**Comment by jackhumbert** [comment]
This is talked about in the [`doc/keymap.md`](https://github.com/jackhumbert/qmk_firmware/blob/master/doc/keymap.md#02-layer-precedence-and-transparency) file - the keycode.txt is really just a quick reference for the keycodes.

**Comment by mystcreater** [comment]
Thanks jack, exactly what I was searching for. :)
