### ISSUE TITLE
LSFT() keys such as KC_ASTR and KC_LPRN put the keyboard in a bad state if shift is held

### ISSUE THREAD

**Issue by ec1oud** [jackhumbert/qmk_firmware#391]
I'm using Ergodox EZ.  I have four such keys on my layout: KC_ASTR,KC_AMPR,KC_LPRN,KC_RPRN.  If I actually hold the shift key when I press one of those keys, I get into a weird state where most typing is impossible (except that the U key sends =, for some reason) and I need to reset the keyboard (re-plug it).

What I would like instead is to be able to assign other keys/macros to the shifted state for those keys.  The ultimate solution might be to treat the shift keys as a layer switch instead of sending shift, and then define what the shifted key will be on that layer.  Is such a thing possible?  And then we might need another definition which means shifted-transparent, KC_STRN or something like that, because in the shift-layer, most letter keys simply need to send shift-character when shift is held.  Only a few keys need special handling of shift, so that a key could be KC_LPRN when shift is not held, and some sort of macro when shift is held.  Whereas the "A" key would be defined as KC_A on the default layer and KC_STRN on the shift layer.

**Comment by eltang** [comment]
Most of what you want is already possible!

Change the `IS_COMMAND()` definition to a different condition or to `0` if you don't use the feature.

You can make a modifier key pop you into another layer every time it's pressed by making it `ACTION_LAYER_MODS(layer, mods)`. I'm not sure I understand your description of `KC_STRN`.

**Comment by ezuk** [comment]
@ec1oud did this help?

**Comment by sergei-dyshel** [comment]
I'm experiencing this problem. I have a layer (#1) which maps number keys to their shifted state (!, @, # etc.). When I'm pressing those keys alone, everything works perfectly. But as soon as I press Shift+number (while still being in that layer), keyboard start behaving strangely and I need to replug it. 

Any ideas?

**Comment by jackhumbert** [comment]
It sounds like your keyboard's entering command mode, and changing the layer (shift + shift + number does this). You can disable command mode with `COMMAND_ENABLE = no` in your `Makefile`.

**Comment by sergei-dyshel** [comment]
It was exactly that! Thanks, Jack!

**Comment by ec1oud** [comment]
COMMAND_ENABLE = no in the Makefile: that works, thanks!

I didn't get around to trying the other suggestions yet.

**Comment by sergei-dyshel** [comment]
Closing :smile:
