### ISSUE TITLE
Relative path change causes compile error on paths with spaces.

### ISSUE THREAD

**Issue by mikelduffy** [jackhumbert/qmk_firmware#403]
Problem occurring on osx for paths with spaces. Compile error that I get is:

`make: *** /Users/username: Is a directory.  Stop.`

Works after moving directory into a path without spaces.

**Comment by jackhumbert** [comment]
This is after [this commit](https://github.com/jackhumbert/qmk_firmware/commit/92759be3226c83087959015be097b66d8c7e2f21)? Do you have the same problem before it?

**Comment by mikelduffy** [comment]
Thanks for such a quick response, and for maintaining such an awesome firmware!

Yes, it was that commit, and no, the problem did not exist previously. I just removed the spaces from my folder hierarchy to avoid such problems in the future.

**Comment by jackhumbert** [comment]
Fixed at c4ea06d!
