### ISSUE TITLE
BL_INC and BL_DEC not working on Satan

### ISSUE THREAD

**Issue by denolfe** [jackhumbert/qmk_firmware#427]
I just recently flashed qmk onto my GH60 Satan board. Everything appears to be working correctly, with the exception of the `BL_INC` and `BL_DEC` commands. Basically, they turn the backlight on or off, without any levels. The `BL_TOGGLE` however works correctly.

Any ideas on what could be going wrong or how to troubleshoot this? Thanks.

**Comment by jackhumbert** [comment]
The backlight for the satan is on or off right now - it'd be possible to implement backlight levels like the Planck has, though. Would you be interested in helping with this?

**Comment by denolfe** [comment]
@jackhumbert. Yes, I can definitely help out.

**Comment by jackhumbert** [comment]
Awesome! Can you try out qmk_firmware/satan-backlight-levels?

**Comment by denolfe** [comment]
Yep, I'll load that this evening and report back.

**Comment by jackhumbert** [comment]
Thanks!

**Comment by denolfe** [comment]
`BL_INC`,`BL_DEC`, and `BL_STEP` all work correctly.

However, the caps lock LED does not adjust along with the rest of the LEDs. I'm not sure if this is intended or not.

I also noticed, that if you use `BL_STEP` all the way through, when going from Off to Level 1, it briefly flashes to max brightness.

All minor things. I'd be perfectly happy if it were merged in this state.

**Comment by jackhumbert** [comment]
That's intended - unfortunately the caps lock LED pin doesn't have PWM control like the backlight does. 

Yeah, that's consistent with other boards - been meaning to look into that!

Thanks for testing! I'll get this merged :)

**Comment by denolfe** [comment]
@jackhumbert Awesome, let me know when you get that LED breathing put in. I'd be happy to test!

**Comment by jackhumbert** [comment]
Will do! I'm working on abstracting that and the main backlight code out now - I should have something for you to mess with later this week.

**Comment by jackhumbert** [comment]
Btw, you can enable the breathing with `#define BACKLIGHT_BREATHING` in your `config.h`. The functions are currently enabled by default (or documented), but you can add them to your keymap! There are some examples [here](https://github.com/jackhumbert/qmk_firmware/blob/master/keyboards/atomic/keymaps/pvc/keymap.c)!

**Comment by denolfe** [comment]
@jackhumbert I wasn't sure of all the steps to get this to work. I added the `#define BACKLIGHT_BREATHING`, but I could not find an example of adding anything breathing related to a keymap. Do you have an example of that? From the link you gave, it looks like a macro that needs to be added? Thanks for the help!

**Comment by jackhumbert** [comment]
Yeap - that's right! [Here's a better example](https://github.com/jackhumbert/qmk_firmware/blob/master/keyboards/planck/keymaps/experimental/keymap.c#L240) - this basically dims the light, then comes back on :)

Do you have your keymap on github? I can give you a diff to try if that's easier!

**Comment by denolfe** [comment]
My keymap is [here](https://github.com/denolfe/qmk_firmware/tree/master/keyboards/satan/keymaps/denolfe). I tried emulating your second example without success.

**Comment by jackhumbert** [comment]
Ah, you might need to pull the latest changes first :)

**Comment by denolfe** [comment]
Hmm, no success. I can try this another time or wait until someone else puts it on their keymap. Thanks for the help!
