### ISSUE TITLE
How do i mount a keyboard or get to /keyboard/ in a shell?

### ISSUE THREAD

**Issue by peterobrien** [jackhumbert/qmk_firmware#43]
I have just received a nice looking ErgoDox EZ, and now I want to change the layout

```
If you're looking to customize a keyboard that currently runs QMK or TMK , find your keyboard's directory under /keyboard/ and read the README file. This will get you all set up.
```

But how do i mount it to be able to find the /keyboard/ folder? It behaves just like a keyboard when i plug it in? There is no volume mounted etc... I'm on a mac

**Comment by jackhumbert** [comment]
Hit CMD+space, type in "Terminal" and that should get you going :)

**Comment by peterobrien** [comment]
➜  ~  cd /keyboard/
cd: no such file or directory: /keyboard/

**Comment by jackhumbert** [comment]
You need to download the firmware, then cd to that folder, then `cd keyboard/` (leave off the leading slash).

**Comment by peterobrien** [comment]
Thanks, making progress.

So I want to change keymap, I have edited `keyboard/ergodox_ez/keymaps/keymap_default.c`. Any tips on how i get that on to the keyboard itself?

**Comment by tdegrunt** [comment]
We have some OSX instructions here: https://github.com/ErgoDox-EZ/reactor#mac-osx
