### ISSUE TITLE
Change the Control keys to Command for Macs

### ISSUE THREAD

**Issue by barryofguilder** [jackhumbert/qmk_firmware#44]
I'm using the Ergodox EZ keyboard and thought that for Mac users, it would be awesome if the Control keys could be changed to Command keys. Could a "Mac" layout be created for this?

**Comment by jackhumbert** [comment]
Are you referencing the Ergodox EZ? We just setup an OSX layout [here](https://github.com/jackhumbert/qmk_firmware/tree/master/keyboard/ergodox_ez/keymaps) that is a good starting point for customising.

**Comment by barryofguilder** [comment]
Yes, thanks!
