### ISSUE TITLE
Strange behaviour of Unicode function.

### ISSUE THREAD

**Issue by Fahrradflucht** [jackhumbert/qmk_firmware#450]
I tried to implement a third layer which enables me to write German umlauts (äöü) and ß, while staying in US key layout. I didn't find another solution to this then mapping the keys in that layer to the corresponding unicode, but the behavior I got was very strange. 

If I hit the key that I mapped to `UC(0x00FC)`, which should be `ü` according to [Wikipedia](https://en.wikipedia.org/wiki/Latin-1_Supplement_(Unicode_block)) I get the following: `ººƒç`

**Comment by algernon** [comment]
What OS are you using? Different operating systems have different unicode input methods, and maybe the default of QMK (osx, I think?) is not suitable for you.

**Comment by Fahrradflucht** [comment]
I use OSX 10.11.5.

On Jun. 27 2016, at 4:10 pm, Gergely Nagy &lt;notifications@github.com&gt;
wrote:  

> What OS are you using? Different operating systems have different unicode
input methods, and maybe the default of QMK (osx, I think?) is not suitable
for you.

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/jackhumbert/qmk_firmware/issues/450#issuecomment-228756535),
or [mute the
thread](https://github.com/notifications/unsubscribe/AMn9nW0vrjpph62b4s03J9tfvmFNvEYGks5qP9nMgaJpZM4I_IHh).![](https://github.com/notifications/beacon
/AMn9nRbtg3xF-QZwHdbNzd04dpyQulY5ks5qP9nMgaJpZM4I_IHh.gif)

**Comment by algernon** [comment]
What happens when you press left alt, then, while held, 00FC, and release alt too? Does that input the correct character, or does ti do the `ººƒç` too?

**Comment by jackhumbert** [comment]
Are you using the Unicode Hex Input? Keyboard > Input Sources > Other (at the bottom) > Unicode Hex Input.

**Comment by Fahrradflucht** [comment]
No I didn't. I was using US layout. Now I works just fine.

Thanks.
