### ISSUE TITLE
Ergodox Supercoder config file is named config_user.h

### ISSUE THREAD

**Issue by fredizzimo** [jackhumbert/qmk_firmware#501]
I will fix this myself, but I just want to confirm that the config_user.h file of the Ergodox EZ supercoder keyboard should be named config.h instead. 

It seems like d9e4dad0a828a8a904f44dda090a4d6d08fe2948 (Makefile redo & other features), removed support for config_user.h, and instead uses only config.h. A lot of other config_user files were renamed, but not that one.

**Comment by jackhumbert** [comment]
Yeap! Sorry about that - must have missed that one.

**Comment by fredizzimo** [comment]
Don't worry, it didn't take much time to find and the fix is part of #503. I can also pull it out to a separate pull request if needed.
