### ISSUE TITLE
Incorrect make invocation in tmk_core/doc/build.md

### ISSUE THREAD

**Issue by chwilk** [jackhumbert/qmk_firmware#51]
Following the directions in build.md, I noticed the `-f Makefile.<variant>` syntax is either wrong or outdated. From what I see in the Makefile for the keyboard/ergodox-ez project, if variant is supposed to be an alternate keymap, the syntax should read `make KEYMAP=<variant>` instead.

**Comment by jackhumbert** [comment]
TMK supports lots of different projects, but I only maintain a couple of them :)
