### ISSUE TITLE
The QK_MODS are too compressed

### ISSUE THREAD

**Issue by fredizzimo** [jackhumbert/qmk_firmware#524]
The QK_MODS are currently defined as 4 bits specifying which kind of modifier key it represents and 1 bit telling if it's right hand or left hand.

This works fine for  most cases, but when you want to combine left hand and right hand mods like this for example `LSFT(kc) | RSFT(kc)`, then right hand bit would be turned on. So in the example, the end result is that only the right hand shift gets pressed.

The issue is not that serious, since macros can be used instead of mods, and the need for this kind of things should be very rare. I don't have the need, at least not right now, but I saw this bug/design decision when reading the code.

I'm not sure if we can afford to use 8 bits for the mods though. But I understand that at some point, you want to move to 32 bit codes, so at least at that point it should be fixed.

**Comment by ezuk** [comment]
IMHO this is a reasonable design choice at this point. Fixing it without a clear use case feels like premature optimization. I'm closing this for now, but we can certainly revisit once we feel the pain. Thank you! :)
