### ISSUE TITLE
how do i debug?

### ISSUE THREAD

**Issue by pvinis** [jackhumbert/qmk_firmware#531]
how can i debug or print debug messages?

i guess i have to enable debug in the makefile, but then how to i connect to it so i see whats printed?

also, can i debug with gdb or something?

**Comment by skullydazed** [comment]
You use hid_listen: https://www.pjrc.com/teensy/hid_listen.html

You can't gdb, but you can print messages to be read by hid_listen.

**Comment by pvinis** [comment]
awesome. thanks

**Comment by pvinis** [comment]
@skullydazed so how do i actually print something?
i need `DEBUG_ENABLE = yes` in the makefile only?

**Comment by skullydazed** [comment]
Looks like you figured this out! I'm not sure if your PR meets all the style reqs, but it's definitely better than what's there now. I'll give @jackhumbert and @ezuk a chance to review (or merge) it before accepting.

**Comment by pvinis** [comment]
indeed I did, and I forgot to close this again. thank you.
