### ISSUE TITLE
Trouble building - no rule to make target

### ISSUE THREAD

**Issue by Lknechtli** [jackhumbert/qmk_firmware#54]
When I run `make clean` then `make KEYMAP=keymap_default` or any other keymap, I get `make: *** No rule to make target 'ergodox_ez.elf', needed by 'elf'.'`
I am running both commands in repo/qmk_firmware/keyboard/ergodox_ez
Tried following the instructions both on linux and windows with the same result - am I doing something wrong?

**Comment by Lknechtli** [comment]
Nevermind ... Docs should be updated to reflect that you only need the part of the filename that comes after "keymap_"
It's just plain misleading right now.

**Comment by ezuk** [comment]
Thank you, @Lknechtli! I changed the wording now -- is it clearer? I appreciate you opening an issue.

**Comment by Lknechtli** [comment]
Looks good to me! I got the replacement left half of my keyboard in the mail today, so I'll check it out when I get home on sunday.  Expect a PR from me sometime soon :)
