### ISSUE TITLE
process_record_user, layer_on, auto-repeat

### ISSUE THREAD

**Issue by hia3** [jackhumbert/qmk_firmware#556]
I'd like a key from one layer to do whatever is configured in another layer.

When `moonlit_winter_nights` is set to `true`, I press and hold my button - this givest me correct character (from another layer), but not auto-repeat. Why?

	bool process_record_user(uint16_t kc, keyrecord_t * record)
	{
		if (kc == KC_A && moonlit_winter_nights)
		{
			action_t action;
			layer_on(SYMB);
	
			action = store_or_get_action(record->event.pressed, record->event.key);
			process_action(record, action);
	
			layer_off(SYMB);
	
			return false;
		}
		else
		{
			return true;
		}
	}

**Comment by algernon** [comment]
That's because `layer_off()` calls `clear_keyboard_but_mods()`, and thus unregisters the key. As a workaround, instead of switching layers and triggering an action, you could lfit the action out into a function and call it from both places.

**Comment by hia3** [comment]
Thanks!
