### ISSUE TITLE
tap-dance: holding a key triggers on_finished every TAPPING_TERM

### ISSUE THREAD

**Issue by algernon** [jackhumbert/qmk_firmware#574]
When a tap-dance key is held, the `on_finished` callback is triggered from the matrix scan every TAPPING_TERM. Ideally, it should only trigger once.

The easiest would be to have a bool that stores whether it was triggered before, but perhaps there's a better way. And in any case, this should only be worked on, once the other tap-dance issues are ironed out, as to not make things worse. Recording this here as an issue, so I don't forget to deal with this too at some point.

**Comment by cdlm** [comment]
BTW, `process_tap_dance.h` needs to `#include "action_tapping.h"` else `TAPPING_TERM` isn't defined

**Comment by algernon** [comment]
Thanks, will add that too!
