### ISSUE TITLE
how to use dvorak for planck easy

### ISSUE THREAD

**Issue by goog** [jackhumbert/qmk_firmware#576]
change the line `bootmagic.c:91:    uint8_t default_layer = 0;`?

**Comment by iFreilicht** [comment]
You shouldn't change anything in the core library if you can avoid it. 

On the Planck, you don't have to program anything to do this. Just hold Lower+Raise and press the key that would be I on QWERTY and N on Dvorak. This will make the Dvorak layer your default base layer, even after unplugging the board. You can look at the _ADJUST-layer [in this file](/jackhumbert/qmk_firmware/blob/master/keyboards/planck/keymaps/default/keymap.c).
