### ISSUE TITLE
Support for version 1.2 of KC60?

### ISSUE THREAD

**Issue by mkraemer** [jackhumbert/qmk_firmware#636]
The PCB of the KC60 i just received from Massdrop is version 1.2 which I haven't seen mentioned anywhere else..
Has anybody experience with using qmk firmware on a non-2.0 KC60?

Thanks :)

**Comment by sgoodwin** [comment]
Can you post a picture of the PCB? Or perhaps check the pin-outs yourself? If the pins for the rows/columns match the 2.0, it should be fine.

**Comment by mkraemer** [comment]
Thanks for your response!
I've attached pictures :)

> Or perhaps check the pin-outs yourself? If the pins for the rows/columns match the 2.0, it should be fine.

Can you point my in the right direction on how to do this?

What's the worst case scenario when flashing qmk to my maybe-not-fully-supported KC60? Non-working rows/column or a bricked and unflashable board?

Thanks again!

![img_20160816_071927](https://cloud.githubusercontent.com/assets/1070200/17688910/a29ea1d0-6383-11e6-923f-b269dd356735.jpg)
![img_20160816_071937](https://cloud.githubusercontent.com/assets/1070200/17688912/a2bbb0a4-6383-11e6-9aea-33b8ecc2afce.jpg)
![img_20160816_071943](https://cloud.githubusercontent.com/assets/1070200/17688913/a2e56c6e-6383-11e6-96b5-b867fc3f4860.jpg)

**Comment by sgoodwin** [comment]
It's the same chip, so your only risk is that certain columns/rows might be in the wrong order. If you trace (like with a finger/something pointy) along the board there from the chip to a row, you'll see which pin is used for which row. You then want to compare that order to the ones used in the 2.0:

rows: { D0, D1, F6, F7, D5 }
columns { F0, F1, E6, C7, C6, B7, D4, B1, B0, B5, B4, D7, D6, B3 }

**Comment by mkraemer** [comment]
Everything seems to be working great!

Awesome! Thank you very much. :+1:
