### ISSUE TITLE
Mouse acceleration broken?

### ISSUE THREAD

**Issue by jacwib** [jackhumbert/qmk_firmware#661]
I put KC_ACL0, KC_ACL1,  KC_ACL2 on the adjust layer of my keymap. However, they do not seem to affect the mouse acceleration of the mouse controls on the keyboard whatsoever.

**Comment by algernon** [comment]
Are you holding those keys while pressing the mouse keys, or you just tap them and release?

**Comment by jacwib** [comment]
Oh, so you're supposed to hold them? That would explain why they did nothing. (I tapped and released)

**Comment by algernon** [comment]
Yep. You can turn them into macros that keep them held until a second tap, if that's more convenient  for you.

(Which is something I always wanted to do, but forgot, so I'm doing it now, thanks for the reminder! :))
