### ISSUE TITLE
Assigning a different character to a key to its shifted version

### ISSUE THREAD

**Issue by dkfi** [jackhumbert/qmk_firmware#72]
Hi Jack,

I'm currently looking into creating a practical italian keyboard layout for the Ergodoz EZ. This is a draft of a desired layout: https://gist.github.com/dkfi/8b71ca2a84af37642231

By looking at Matthias Schmitt contribution on the german layout I still couldn't figure out how to arbitrarily assign a specific character to a shifted key. For instance, based on the gist above, I would like to have the `#` symbol and the '@' on the same key next to ENTER. Any pointer or suggestion?

Thanks!

**Comment by jackhumbert** [comment]
This can be accomplished by a custom function layer that acts as a shift layer (using `S()` on most keys), and a "shift" key that momentarily switches to that layer (like `MO(<layer_number>)`).
