### ISSUE TITLE
Create another S() and similar functions to affect only one keypress

### ISSUE THREAD

**Issue by jackhumbert** [jackhumbert/qmk_firmware#75]
Effectively being:

    MACRO(DOWN(<mod>), TAP(<kc>), UP(<mod>))

**Comment by Eric-L-T** [comment]
Will keys that use this still repeat?

**Comment by jackhumbert** [comment]
Nope :/ it'll be either-or - repeating is handled on the OS side of things.

**Comment by Eric-L-T** [comment]
So there is no way to program keyboards to indicate that keys that use this are held down beyond their initial presses?

**Comment by Eric-L-T** [comment]
Or, can the current programming of S() be retained and add something to make Shift release when any other key is pressed?

**Comment by jackhumbert** [comment]
That was my motive when renaming the issue - releasing shift on another keypress would have more problems than it's worth if you're worried about key repeating (e.g. $$$$4444 after another keypress).

I think the best solution for this is some sort of firmware/OS tandem solution, but I'll keep this request for a oneshot `S(<kc>)` equivalent open.

**Comment by Eric-L-T** [comment]
Well, signifying that a letter keys, whether lowercase or capital, is pretty important when using OS X - it makes a menu for selecting a special version of that letter pop up.

**Comment by eltang** [comment]
This issue can be closed. I have already implemented it.
