### ISSUE TITLE
[kc60] mapping caps lock to LCTL

### ISSUE THREAD

**Issue by tomb0y** [jackhumbert/qmk_firmware#754]
Using [this](https://github.com/jackhumbert/qmk_firmware/blob/master/keyboards/kc60/keymaps/workman-dead/keymap.c) keymap I can't seem to change caps lock to work as control.

For a while I thought it was working, but then it turned out it was because of the osx modifier key settings.

Am I doing something wrong in the keymap, or is this something that can't be done?

**Comment by sgoodwin** [comment]
Everything else works as expected except for that one key?

**Comment by tomb0y** [comment]
@sgoodwin yes, everything else works as expected, but sadly caps lock works as a caps lock, and not ctrl.

**Comment by sgoodwin** [comment]
This is odd, on my kc60 I made the capslock key into an FN key with no trouble. The other control works? You're sure the board has been flashed with this change? (easy mistake to make, either not compiling again or not flashing the latest hex after the compiling)

**Comment by tomb0y** [comment]
Yep, the other ctrl keys works normally.

I flashed the up to date firmware just now to be sure, but nothing changed.
I also tried setting it to `KC_A`, just to try something else out, which works, and strangely enough,  so does `KC_RCTL` which I should have tried out earlier, cause it kinda solves the problem.

I can't get `KC_LCTL` to work though.

**Comment by sgoodwin** [comment]
Ah weird. Why not just use RCTL then?

**Comment by tomb0y** [comment]
Yeah, that's what I'll do, thanks for being the rubber duck @sgoodwin 👍
