### ISSUE TITLE
Led status on atomic/planck

### ISSUE THREAD

**Issue by mecanogrh** [jackhumbert/qmk_firmware#777]
Need to disable the Led Status so I can use the E6 pin on planck/atomic but had no luck locating it in the code, any help?

**Comment by jackhumbert** [comment]
Check out the atomic.c and planck.c files - you can remove this block to allow use of E6:

    // Turn status LED on
    DDRE |= (1<<6);
    PORTE |= (1<<6);

**Comment by mecanogrh** [comment]
Thanks a lot ;)
