### ISSUE TITLE
Usage of LCTL/LSFT/LALT/LGUI in a temporary layers

### ISSUE THREAD

**Issue by DidierLoiseau** [jackhumbert/qmk_firmware#81]
I just noticed an issue if you use those in a temporary layer, for example to provide _cut/copy/paste_ with `LSFT(KC_DELT),LCTL(KC_INS),LSFT(KC_INS)`.

If the user releases the temporary layer key before e.g. the `LSFT(KC_DELT)`, the keyboard starts to send continuous KeyPress/KeyRelease events for `KC_DELT`, and does not send a _Shift_ KeyRelease event.

This is annoying as it makes the usage of LCTL/LSFT/LALT/LGUI unreliable in temporary layers for quick actions.

As a workaround I think using a macro instead should work but it's a bit of a shame though.

**Comment by jackhumbert** [comment]
I think those macros are sufficient - this won't be able to be addressed without changing the TMK base or rewriting a bit.
