### ISSUE TITLE
Ignore Matrix Keys

### ISSUE THREAD

**Issue by IBNobody** [jackhumbert/qmk_firmware#845]
I ran into an issue on my build where I needed to ignore keys on my matrix. I have key switch suppressors that snap onto my keys and make them act as "dead" keys. Without this change, I was unable to put my computer to sleep.

Here is my solution, in a nutshell.

Keymap

```
#define MATRIX_MASKED
const matrix_row_t matrix_mask[MATRIX_ROWS] =
{
//  1098765432109876543210987654321
  0b0000000001111111101111011111111,
  0b0000000001111111111111111111111,
  0b0000000001111111111111111111111,
  0b0000000001111111111111111111111,
  0b0000000001010111111111111111111,
  0b0000000001111101111111101011111,
};
```

```
matrix_row_t matrix_get_row(uint8_t row)
{
    // Matrix mask lets you disable switches in the returned matrix data. For example, if you have a
    // switch blocker installed and the switch is always pressed.
#ifdef MATRIX_MASKED
    return matrix[row] & matrix_mask[row];
#else
    return matrix[row];
#endif
}
```

**Comment by OferPlesser** [comment]
Wouldn't defining the suppressed keys as KC_NO in your keymap suffice?

**Comment by IBNobody** [comment]
No. That only makes keys do nothing when pressed. It does not block the
detection of them being pressed.

**Comment by Wilba6582** [comment]
Is this the cause of the issue you had with the backlight staying on while in suspend mode?

**Comment by IBNobody** [comment]
This was a different issue. There is code in the suspend logic that scans
the matrix to see if a key is pressed. Any key fires it, even KC_NO. If key
blanks are used, they will be detected as key down events and cause the
host computer to be woken up.

**Comment by piotr-dobrogost** [comment]
> I have key switch suppressors that snap onto my keys and make them act as "dead" keys.

How come you did not attach picture of them? :-)

**Comment by IBNobody** [comment]
There were other ways to handle it, but having a matrix mask was the least
intrusive. It has to be enabled, and it is very process efficient.

**Comment by IBNobody** [comment]
@piotr-dobrogost 

Here:

http://pimpmykeyboard.com/switch-blocker-pack-of-10/

They snap onto the switch base. They always keep the switch pressed down.

**Comment by piotr-dobrogost** [comment]
Thanks for picture. What's the purpose of disabling some keys? Btw, you described these as *dead* keys which has specific meaning in the context of keyboards – https://en.wikipedia.org/wiki/Dead_key

**Comment by IBNobody** [comment]
I have a grid keyboard, and I wanted to mask off some keys. For example, I have a row of 14 keys that I use for my F keys. I have these switch blockers installed between F4 and F5, and between F8 and F9. They make the keyboard easier to use because I can find the right F key blindly. 

It also allowed me to convert those blocked switches into normal switches if I ever wanted to use them. I just pop off the blockers and put on a keycap.

But... Law of unintended consequences... I didn't realize that QMK would sense them as pressed and wake the computer. By masking the matrix, I can force them to be inactive.

**Comment by IBNobody** [comment]
I am closing this issue, though because I implemented the mask.
