### ISSUE TITLE
Tap Dance + OSM

### ISSUE THREAD

**Issue by kthibodeaux** [jackhumbert/qmk_firmware#859]
When I try to use tap dancing with OSM it doesn't work.  If I have `ACTION_TAP_DANCE_DOUBLE(KC_Z, OSM(MOD_LSFT))` it does nothing.  If I have `ACTION_TAP_DANCE_DOUBLE(KC_Z, OSM(MOD_LGUI))` then the second tap outputs `e`.

I also tried setting it up in the action like i have SCLN and SPC but got nothing there, either.

The end goal is to have zz make the next keypress modified by CMD, but tapping then holding z act as CMD until released.

My full setup is here: https://github.com/kthibodeaux/ergodox-layout/blob/tap-dance-z-for-osm-cmd/keymap.c

**Comment by algernon** [comment]
`ACTION_TAP_DANCE_DOUBLE` expects both arguments to be plain keycodes, with modifiers applied at best. It does not support other actions like OSM. To have an OSM effect applied, you'll have to use your own custom tap-dance functions.

Something along these lines:

```c
case TD(Z):
  if (state->count == 1) {
    register_code (KC_Z);
    unregister_code(KC_Z);
  } else {
    set_oneshot_mods (MOD_LGUI);
  }
  break;
```

**Comment by kthibodeaux** [comment]
Thanks algernon, you rock!
