### ISSUE TITLE
KC_PWR not working

### ISSUE THREAD

**Issue by Wilba6582** [jackhumbert/qmk_firmware#900]
It was working for me in TMK, i.e. KC_PWR in my keymap would put my PC to sleep. But in QMK, it's not doing anything. Media controls KC_MUTE, KC_VOLU, KC_VOLD are working.

Not ruling out that it's just my config at fault, so hopefully someone can reproduce on their own keyboard.

**Comment by jackhumbert** [comment]
Which keyboard/keymap are you trying it with?

**Comment by Wilba6582** [comment]
My Zeal60, but it fails on Planck as well (just tested).
