### ISSUE TITLE
Output too large after recent changes

### ISSUE THREAD

**Issue by NoahAndrews** [jackhumbert/qmk_firmware#920]
I was wanting to play around with the just-merged SysEx API, but when I try to flash the updated firmware with [my custom keymap](https://github.com/NoahAndrews/qmk_firmware/tree/master/keyboards/planck/keymaps/noah), I get an error saying "Bootloader and code overlap", implying that the firmware is now too large. I suspect this is due to #918.  Perhaps there should be a way to exclude the new API from the firmware to save space.

**Comment by jackhumbert** [comment]
I think it's setup to disable it via `API_SYSEX_ENABLE=no` in the Makefile. I'm also looking to minimise the footprint though :)

**Comment by jackhumbert** [comment]
Oops - the one in rules.mk should have a `?=` - that should allow you to override it, I believe (it might not be possible otherwise)

**Comment by NoahAndrews** [comment]
It worked fine as-is actually, thanks

**Comment by cbbrowne** [comment]
Can we have it disabled by default, and only enable it if it's set to "yes"?  That would mean we don't run into this a bunch of times when various people update their favorite layouts.
