### ISSUE TITLE
bone2planck keyboard too big, probably needs parm changes

### ISSUE THREAD

**Issue by cbbrowne** [jackhumbert/qmk_firmware#925]
Creating load file for Flash: .build/planck_rev4_bone2planck.hex                                    [OK]

Size after:
   text    data     bss     dec     hex filename
      0   29088       0   29088    71a0 planck_rev4_bone2planck.hex

Bigger than 7000h maximum, so it probably needs to have the Makefile revised to deactivate API_SYSEX_ENABLE, or similar.

**Comment by jackhumbert** [comment]
Addressed in #929
