### ISSUE TITLE
brandon keyboard too large, probably needs compile parm changes

### ISSUE THREAD

**Issue by cbbrowne** [jackhumbert/qmk_firmware#926]
Creating load file for Flash: .build/planck_rev4_brandon.hex                                        [OK]

Size after:
   text    data     bss     dec     hex filename
      0   28696       0   28696    7018 planck_rev4_brandon.hex

7018h > 7000h, so that probably won't load.  Suggestion: Take a look at parms in Makefile, it probably needs to have the Makefile revised to deactivate API_SYSEX_ENABLE, or similar.

**Comment by jackhumbert** [comment]
Addressed in #929
