### ISSUE TITLE
impossible planck keymap generates too-large .hex, needs build parm changes

### ISSUE THREAD

**Issue by cbbrowne** [jackhumbert/qmk_firmware#927]
Creating load file for Flash: .build/planck_rev4_impossible.hex                                     [OK]

Size after:
   text    data     bss     dec     hex filename
      0   29638       0   29638    73c6 planck_rev4_impossible.hex

73c6h > 7000h, so that probably won't load. Suggestion: Take a look at parms in Makefile, it probably needs to have the Makefile revised to deactivate API_SYSEX_ENABLE, or similar.

**Comment by jackhumbert** [comment]
Addressed in #929
