### ISSUE TITLE
apt-get upgrade in install_dependancies.sh

### ISSUE THREAD

**Issue by illuminatio** [jackhumbert/qmk_firmware#970]
I know, shame on me for blindly launching this file, but really, was it fucking necessary? Without even a prompt?

**Comment by jackhumbert** [comment]
It's my understanding that `apt-get upgrade` is fairly standard for these installation scripts. I've added a warning about it to the wiki.

**Comment by khogeland** [comment]
@jackhumbert I have never seen an installation script attempt to blindly run `apt-get upgrade`. Attempting to run this for a user can cause unexpected and unwanted changes, break things, or anything else... This is 100% not QMK's responsibility.
