### ISSUE TITLE
set audio pin

### ISSUE THREAD

**Issue by illtown** [jackhumbert/qmk_firmware#992]
I wonder if there is a way to redefine the audio pin, which is C6 by default, but on my ergodox it's responsible for the last column. C7 could be a good choice, instead.

**Comment by xream** [comment]
I think you may check this issue #414.

**Comment by jackhumbert** [comment]
It is! Right now C6 is built into the audio.c code, but I think that could be abstracted to allow for C7 and other pins/timers to be used :)

**Comment by illtown** [comment]
Thanks a lot guys, at least I now know where to look for it. The audio is not the first in my tweaking list )
